Feature/service menu
geneus-solutions/geneus-web pull request #3
Opened 2024-10-01 07:11 UTC by vikram2141

dropdown menu change multilevel dropdown @jagadishsail

2024-10-06 10:46 UTC, geneus-solutions requested changes

2024-10-06 10:46 UTC, geneus-solutions commented on client/src/components/MenuItems/MenuItems.jsx
> +                <Link to="/nutriapp">Nutritional</Link>
Why this Menu Nutritional extra? As discussed this should be part of Services

2024-10-06 10:46 UTC, geneus-solutions commented on client/src/components/Nutrifit/Nutrifit.jsx
> +import NutriFitImage from '../../assets/nutrifit.jpeg';
Why this file added NutriFit?

2024-10-06 10:46 UTC, geneus-solutions commented on client/src/components/Services/Services.jsx
> +  )
Why this file Services.jsx?

2024-10-06 10:46 UTC, geneus-solutions commented on client/src/menuItemsData.js
> +    {
in which component this file is used? client/src/menuItemsData.js

2024-10-14 07:19 UTC, vikram2141 commented
Update

2024-10-19 14:34 UTC, closed without merging